/*
 * Copyright (c) 2011-2013, Peter Abeles. All Rights Reserved.
 *
 * This file is part of BoofCV (http://boofcv.org).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package boofcv.alg.enhance.impl;

import boofcv.misc.AutoTypeImage;
import boofcv.misc.CodeGeneratorBase;

import java.io.FileNotFoundException;

/**
 * @author Peter Abeles
 */
public class GenerateImplEnhanceFilter extends CodeGeneratorBase {
	String className = "ImplEnhanceFilter";

	public GenerateImplEnhanceFilter() throws FileNotFoundException {
		setOutputFile(className);
	}

	@Override
	public void generate() throws FileNotFoundException {
		printPreamble();

		sharpen4(AutoTypeImage.U8);
		sharpen4(AutoTypeImage.F32);
		sharpen8(AutoTypeImage.U8);
		sharpen8(AutoTypeImage.F32);

		out.print("\n" +
				"}\n");
	}

	private void printPreamble() {
		out.print("import boofcv.struct.convolve.Kernel2D_F32;\n" +
				"import boofcv.struct.convolve.Kernel2D_I32;\n" +
				"import boofcv.struct.image.*;\n" +
				"\n" +
				"/**\n" +
				" * <p>\n" +
				" * Filter based functions for image enhancement.\n" +
				" * </p>\n" +
				" *\n" +
				" * <p>\n" +
				" * NOTE: Do not modify.  Automatically generated by {@link GenerateImplEnhanceFilter}.\n" +
				" * </p>\n" +
				" *\n" +
				" * @author Peter Abeles\n" +
				" */\n" +
				"public class ImplEnhanceFilter {\n" +
				"\n" +
				"\tpublic static Kernel2D_I32 kernelEnhance4_I32 = new Kernel2D_I32(3, new int[]{0,-1,0,-1,5,-1,0,-1,0});\n" +
				"\tpublic static Kernel2D_F32 kernelEnhance4_F32 = new Kernel2D_F32(3, 0,-1,0,-1,5,-1,0,-1,0);\n" +
				"\tpublic static Kernel2D_I32 kernelEnhance8_I32 = new Kernel2D_I32(3, new int[]{-1,-1,-1,-1,9,-1,-1,-1,-1});\n" +
				"\tpublic static Kernel2D_F32 kernelEnhance8_F32 = new Kernel2D_F32(3, -1,-1,-1,-1,9,-1,-1,-1,-1);\n\n");
	}

	private void sharpen4(AutoTypeImage image) {
		String name = image.getImageName();
		String bitwise = image.getBitWise();
		String cast = image.getTypeCastFromSum();
		String sumtype = image.getSumType();

		out.print("\tpublic static void sharpenInner4( "+name+" input , "+name+" output , "+sumtype+" minValue , "+sumtype+" maxValue ) {\n" +
				"\t\tfor( int y = 1; y < input.height-1; y++ ) {\n" +
				"\t\t\tint indexIn = input.startIndex + y*input.stride + 1;\n" +
				"\t\t\tint indexOut = output.startIndex + y*output.stride + 1;\n" +
				"\n" +
				"\t\t\tfor( int x = 1; x < input.width-1; x++ , indexIn++,indexOut++) {\n" +
				"\n" +
				"\t\t\t\t"+sumtype+" a = 5*(input.data[indexIn] "+bitwise+") - (\n" +
				"\t\t\t\t\t\t(input.data[indexIn-1] "+bitwise+")+(input.data[indexIn+1] "+bitwise+") +\n" +
				"\t\t\t\t\t\t\t\t(input.data[indexIn-input.stride] "+bitwise+") + (input.data[indexIn+input.stride] "+bitwise+"));\n" +
				"\n" +
				"\t\t\t\tif( a > maxValue )\n" +
				"\t\t\t\t\ta = maxValue;\n" +
				"\t\t\t\telse if( a < minValue )\n" +
				"\t\t\t\t\ta = minValue;\n" +
				"\n" +
				"\t\t\t\toutput.data[indexOut] = "+cast+"a;\n" +
				"\t\t\t}\n" +
				"\t\t}\n" +
				"\t}\n\n");
	}

	private void sharpen8(AutoTypeImage image) {
		String name = image.getImageName();
		String bitwise = image.getBitWise();
		String cast = image.getTypeCastFromSum();
		String sumtype = image.getSumType();

		out.print("\tpublic static void sharpenInner8( "+name+" input , "+name+" output , "+sumtype+" minValue , "+sumtype+" maxValue ) {\n" +
				"for( int y = 1; y < input.height-1; y++ ) {\n" +
				"\t\t\tint indexIn = input.startIndex + y*input.stride + 1;\n" +
				"\t\t\tint indexOut = output.startIndex + y*output.stride + 1;\n" +
				"\n" +
				"\t\t\tfor( int x = 1; x < input.width-1; x++ , indexIn++,indexOut++) {\n" +
				"\n" +
				"\t\t\t\t"+sumtype+" a11 = input.data[indexIn-input.stride-1] "+bitwise+";\n" +
				"\t\t\t\t"+sumtype+" a12 = input.data[indexIn-input.stride] "+bitwise+";\n" +
				"\t\t\t\t"+sumtype+" a13 = input.data[indexIn-input.stride+1] "+bitwise+";\n" +
				"\t\t\t\t"+sumtype+" a21 = input.data[indexIn-1] "+bitwise+";\n" +
				"\t\t\t\t"+sumtype+" a22 = input.data[indexIn] "+bitwise+";\n" +
				"\t\t\t\t"+sumtype+" a23 = input.data[indexIn+1] "+bitwise+";\n" +
				"\t\t\t\t"+sumtype+" a31 = input.data[indexIn+input.stride-1] "+bitwise+";\n" +
				"\t\t\t\t"+sumtype+" a32 = input.data[indexIn+input.stride] "+bitwise+";\n" +
				"\t\t\t\t"+sumtype+" a33 = input.data[indexIn+input.stride+1] "+bitwise+";\n" +
				"\t\t\t\t\n" +
				"\t\t\t\t"+sumtype+" result = 9*a22 - (a11+a12+a13+a21+a23+a31+a32+a33);\n" +
				"\n" +
				"\t\t\t\tif( result > maxValue )\n" +
				"\t\t\t\t\tresult = maxValue;\n" +
				"\t\t\t\telse if( result < minValue )\n" +
				"\t\t\t\t\tresult = minValue;\n" +
				"\n" +
				"\t\t\t\toutput.data[indexOut] = "+cast+"result;\n" +
				"\t\t\t}\n" +
				"\t\t}\n" +
				"\t}\n\n");
	}

	public static void main( String args[] ) throws FileNotFoundException {
		GenerateImplEnhanceFilter app = new GenerateImplEnhanceFilter();
		app.generate();
	}
}
