/*
 * Copyright (c) 2011-2012, Peter Abeles. All Rights Reserved.
 *
 * This file is part of BoofCV (http://boofcv.org).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package boofcv.alg.distort.impl;

import boofcv.misc.AutoTypeImage;
import boofcv.misc.CodeGeneratorBase;

import java.io.FileNotFoundException;


/**
 * @author Peter Abeles
 */
public class GeneratorImplImageDistort extends CodeGeneratorBase {
	String className;

	AutoTypeImage image;

	@Override
	public void generate() throws FileNotFoundException {
		createType(AutoTypeImage.F32);
		createType(AutoTypeImage.I8);
		createType(AutoTypeImage.I16);
		createType(AutoTypeImage.S32);
	}

	private void createType( AutoTypeImage type ) throws FileNotFoundException {
		className = "ImplImageDistort_"+type.name();
		image = type;

		createFile();
	}

	private void createFile() throws FileNotFoundException {
		printPreamble();
		printFunction();
		printFunctionCrop();
		printDistort();
		printNoBorderDistort();
		out.println("}");
	}

	private void printPreamble() throws FileNotFoundException {

		String imageName = image.getImageName();
		String borderType = image.isInteger() ? "ImageBorder_I32" : "ImageBorder_F32";
		String borderImageType = image.isInteger() ? "ImageInteger" : imageName;

		setOutputFile(className);
		out.print("import boofcv.alg.interpolate.InterpolatePixel;\n" +
				"import boofcv.alg.distort.ImageDistort;\n" +
				"import boofcv.struct.image."+imageName+";\n" +
				"import boofcv.struct.distort.PixelTransform_F32;\n" +
				"import boofcv.core.image.border.ImageBorder;\n" +
				"import boofcv.core.image.border."+borderType+";\n");
		if( image.isInteger() ) {
			out.print("import boofcv.struct.image.ImageInteger;\n");
		}
		out.print("\n" +
				"\n" +
				"/**\n" +
				" * <p>Implementation of {@link boofcv.alg.distort.ImageDistort}.</p>\n" +
				" *\n" +
				" * <p>\n" +
				" * DO NOT MODIFY: Generated by {@link boofcv.alg.distort.impl.GeneratorImplImageDistort}.\n" +
				" * </p>\n" +
				" *\n" +
				" * @author Peter Abeles\n" +
				" */\n" +
				"@SuppressWarnings({\"UnnecessaryLocalVariable\"})\n");
		if( image.isInteger() ) {
			out.print("public class "+className+"<T extends "+imageName+"> implements ImageDistort<T> {\n");
			imageName = "T";
		} else {
			out.print("public class "+className+" implements ImageDistort<"+imageName+"> {\n");
		}

		out.print("\n" +
				"\t// transform from dst to src image\n" +
				"\tprivate PixelTransform_F32 dstToSrc;\n" +
				"\t// sub pixel interpolation\n" +
				"\tprivate InterpolatePixel<"+imageName+"> interp;\n" +
				"\t// handle the image border\n" +
				"\tprivate "+borderType+" border;\n" +
				"\n" +
				"\t// crop boundary\n" +
				"\tint x0,y0,x1,y1;\n" +
				"\n" +
				"\tpublic "+className+"(PixelTransform_F32 dstToSrc, InterpolatePixel<"+imageName+"> interp , ImageBorder<"+borderImageType+"> border ) {\n" +
				"\t\tthis.dstToSrc = dstToSrc;\n" +
				"\t\tthis.interp = interp;\n" +
				"\t\tthis.border = ("+borderType+")border;\n" +
				"\t}\n"+
				"\n" +
				"\t@Override\n" +
				"\tpublic void setModel(PixelTransform_F32 dstToSrc) {\n" +
				"\t\tthis.dstToSrc = dstToSrc;\n" +
				"\t}\n\n");
	}

	private void printFunction() {

		String imageName = image.isInteger() ? "T" : image.getImageName();

		out.print("\t@Override\n" +
				"\tpublic void apply( "+imageName+" srcImg , "+imageName+" dstImg ) {\n" +
				"\t\tinterp.setImage(srcImg);\n" +
				"\n" +
				"\t\tx0 = 0;y0 = 0;x1 = dstImg.width;y1 = dstImg.height;\n" +
				"\n" +
				"\t\tif( border != null )\n" +
				"\t\t\tapplyBorder(srcImg, dstImg);\n" +
				"\t\telse\n" +
				"\t\t\tapplyNoBorder(srcImg, dstImg);\n" +
				"\t}\n\n");
	}

	private void printFunctionCrop() {

		String imageName = image.isInteger() ? "T" : image.getImageName();

		out.print("\t@Override\n" +
				"\tpublic void apply( "+imageName+" srcImg , "+imageName+" dstImg , int dstX0, int dstY0, int dstX1, int dstY1 ) {\n" +
				"\t\tinterp.setImage(srcImg);\n" +
				"\n" +
				"\t\tx0 = dstX0;y0 = dstY0;x1 = dstX1;y1 = dstY1;\n" +
				"\n" +
				"\t\tif( border != null )\n" +
				"\t\t\tapplyBorder(srcImg, dstImg);\n" +
				"\t\telse\n" +
				"\t\t\tapplyNoBorder(srcImg, dstImg);\n" +
				"\t}\n\n");
	}

	private void printDistort() {

		String typeCast = image.isInteger() ? "("+image.getDataType()+")" : "";
		String imageName = image.isInteger() ? "T" : image.getImageName();

		out.print("\tpublic void applyBorder( "+imageName+" srcImg , "+imageName+" dstImg ) {\n" +
				"\n" +
				"\t\tborder.setImage(srcImg);\n" +
				"\n" +
				"\t\tfinal float minInterpX = interp.getUnsafeBorderX();\n" +
				"\t\tfinal float minInterpY = interp.getUnsafeBorderY();\n" +
				"\t\tfinal float maxInterpX = srcImg.getWidth()-interp.getUnsafeBorderX();\n" +
				"\t\tfinal float maxInterpY = srcImg.getHeight()-interp.getUnsafeBorderY();\n" +
				"\n" +
				"\t\tfinal float widthF = srcImg.getWidth();\n" +
				"\t\tfinal float heightF = srcImg.getHeight();\n" +
				"\n" +
				"\t\tfor( int y = y0; y < y1; y++ ) {\n" +
				"\t\t\tint indexDst = dstImg.startIndex + dstImg.stride*y + x0;\n" +
				"\t\t\tfor( int x = x0; x < x1; x++ , indexDst++ ) {\n" +
				"\t\t\t\tdstToSrc.compute(x,y);\n" +
				"\n" +
				"\t\t\t\tfinal float sx = dstToSrc.distX;\n" +
				"\t\t\t\tfinal float sy = dstToSrc.distY;\n" +
				"\n" +
				"\t\t\t\tif( sx < minInterpX || sx >= maxInterpX || sy < minInterpY || sy >= maxInterpY ) {\n" +
				"\t\t\t\t\tif( sx >= 0f && sx < widthF && sy >= 0f && sy < heightF )\n" +
				"\t\t\t\t\t\tdstImg.data[indexDst] = "+typeCast+"interp.get(sx,sy);\n" +
				"\t\t\t\t\telse\n" +
				"\t\t\t\t\t\tdstImg.data[indexDst] = "+typeCast+"border.getOutside((int)sx,(int)sy);\n" +
				"\t\t\t\t} else {\n" +
				"\t\t\t\t\tdstImg.data[indexDst] = "+typeCast+"interp.get_unsafe(sx,sy);\n" +
				"\t\t\t\t}\n" +
				"\t\t\t}\n" +
				"\t\t}\n" +
				"\t}\n\n");
	}

	private void printNoBorderDistort() {

		String typeCast = image.isInteger() ? "("+image.getDataType()+")" : "";
		String imageName = image.isInteger() ? "T" : image.getImageName();

		out.print("\tpublic void applyNoBorder( "+imageName+" srcImg , "+imageName+" dstImg ) {\n" +
				"\n" +
				"\t\tfinal float minInterpX = interp.getUnsafeBorderX();\n" +
				"\t\tfinal float minInterpY = interp.getUnsafeBorderY();\n" +
				"\t\tfinal float maxInterpX = srcImg.getWidth()-interp.getUnsafeBorderX();\n" +
				"\t\tfinal float maxInterpY = srcImg.getHeight()-interp.getUnsafeBorderY();\n" +
				"\n" +
				"\t\tfinal float widthF = srcImg.getWidth();\n" +
				"\t\tfinal float heightF = srcImg.getHeight();\n" +
				"\n" +
				"\t\tfor( int y = y0; y < y1; y++ ) {\n" +
				"\t\t\tint indexDst = dstImg.startIndex + dstImg.stride*y + x0;\n" +
				"\t\t\tfor( int x = x0; x < x1; x++ , indexDst++ ) {\n" +
				"\t\t\t\tdstToSrc.compute(x,y);\n" +
				"\n" +
				"\t\t\t\tfinal float sx = dstToSrc.distX;\n" +
				"\t\t\t\tfinal float sy = dstToSrc.distY;\n" +
				"\n" +
				"\t\t\t\tif( sx < minInterpX || sx >= maxInterpX || sy < minInterpY || sy >= maxInterpY ) {\n" +
				"\t\t\t\t\tif( sx >= 0f && sx < widthF && sy >= 0f && sy < heightF )\n" +
				"\t\t\t\t\t\tdstImg.data[indexDst] = "+typeCast+"interp.get(sx,sy);\n"+
				"\t\t\t\t} else {\n" +
				"\t\t\t\t\tdstImg.data[indexDst] = "+typeCast+"interp.get_unsafe(sx,sy);\n" +
				"\t\t\t\t}\n" +
				"\t\t\t}\n" +
				"\t\t}\n" +
				"\t}\n\n");
	}

	public static void main( String args[] ) throws FileNotFoundException {
		GeneratorImplImageDistort gen = new GeneratorImplImageDistort();
		gen.generate();
	}
}
