dependencies {
	api project(':main:boofcv-ip')
	api project(':main:boofcv-io')
	api project(':main:boofcv-geo')
    
	api project(':integration:boofcv-swing')

	implementation group: 'org.bytedeco', name: 'opencv-platform', version: '4.10.0-1.5.11'
}

sourceSets { test { java { srcDir 'src/main/examples' } } }
