dependencies {
	api project(':main:boofcv-ip')
	api project(':main:boofcv-recognition')

	['main','models','io'].each {String a ->
		api( group: 'org.deepboof', name: a, version: project.deepboof_version) {
			exclude group: 'com.thoughtworks.xstream'
			exclude group: 'org.ddogleg'
			exclude group: 'org.georegression'
			exclude group: 'org.ejml'
		}}
}
