
dependencies {
	api project(':main:boofcv-ip')
	api project(':main:boofcv-io')
	api project(':integration:boofcv-swing')

	api("com.github.sarxos:webcam-capture:0.3.12") { exclude group: 'org.slf4j' }

	testImplementation project(':main:boofcv-geo')
	testImplementation project(':main:boofcv-feature')
	testImplementation project(':main:boofcv-recognition')
}

sourceSets {
	test {
		java {
			srcDir 'test'
			srcDir 'examples'
		}
		resources {
			srcDir 'resources/test'
		}
	}
}
