# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ SNAPSHOT ]
  pull_request:
    branches: [ SNAPSHOT ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test Spotless
      run: ./gradlew spotlessJavaCheck
    - name: Auto Generate Code
      run: ./gradlew autogenerate
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Print Dependency Info
      run: ./gradlew -q --console plain dependencyInfo
    - name: Unit Tests
      run: ./gradlew test
